In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("pandas version:", pd.__version__)
#print("matplotlib.pyplot version:", plt.__version__)
print("seaborn version:", sns.__version__)

pandas version: 2.3.2
seaborn version: 0.13.2

In [3]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None

This data is gathered from this website: https://www.rijdendetreinen.nl/en/open-data/train-archive

### Data Dictionary

Below you will find the data dictionary provided by Rijden-de-treinen.

Each row in these files represent a stop at a station. Each service at least departs from and arrives at a station (i.e. two rows). For each stop, you can find the name of the station, the arrival and departure time, delays and cancellations. The exact meaning of each column is explained below.

The source for this data is the real-time data from NS with live departure times, live arrival times and service updates. This data is also used in the app and website of Rijden Treinen.

#### Columns
- `Service:RDT-ID` *Unique identifier (service):* This is the ID that Rijden de Treinen uses for this service. It has no useful meaning beyond uniquely identifying a single service on a single date. This ID will occur more than once in the CSV files because this ID is unique for each service. There is also a column Stop:RDT-ID with a unique ID for each stop.
- `Service:Date` *Service date (schedule date):* The scheduled service date for this service. The service date is not always the same as the actual date. For example, a service that departs at 23:59 on 31 July and arrives at 02:00 on 1 August has a service date of 31 July. Delays do not affect the service date.
- `Service:Type` *Service type:* The service type, for example: *Intercity*, *Sprinter* or *ICE International*.
- `Service:Company` *Operator:* Company operating this service, like NS or Arriva.
- `Service:Train number` *Train number:* The train number (service number) for this service uniquely identifies this service on this date. This number is sometimes also communicated to passengers (especially for international trains). A single service may sometimes have multiple train numbers. For example, when a train is split in two parts, or when a train changes a train number on a major station halfway.
- `Service:Completely cancelled` *Service is fully cancelled:* This column is true when all stops of this service have been cancelled. Or in other words: when the train does not run at all.
- `Service:Partly cancelled` *Partially cancelled:* This column is true when one or more stops of this service have been cancelled. Or in other words: when the train does not run on a part of the route.
- `Service:Maximum delay` *Highest delay for this service:* The highest delay (**in minutes**) of all stops of this service.
- `Stop:RDT-ID` *Unique identifier (stop):* Unique identifier for this stop. This ID is unique for each stop in the dataset. It has no further useful meaning.
- `Stop:Station code` *Station code:* Code (abbreviation) of the station name. See also the [dataset with railway stations.](https://www.rijdendetreinen.nl/en/open-data/stations)
- `Stop:Station name` *Station name:* The name of the station.
- `Stop:Arrival time` *Arrival time:* Scheduled arrival time in **RFC 3339 format.** This column is empty when no arrival was scheduled.
- `Stop:Arrival delay` *Arrival delay:* Arrival delay **in minutes.** This column is empty when no arrival was scheduled.
- `Stop:Arrival cancelled` *Cancelled arrival:* This column is true when the arrival at this stop has been cancelled. This column is empty when no arrival was scheduled.
- `Stop:Departure time` *Departure time:* Scheduled departure time in **RFC 3339 format.** This column is empty when no departure was scheduled.
- `Stop:Departure delay` *Departure delay:* Departure delay **in minutes.** This column is empty when no departure was scheduled.
- `Stop:Departure cancelled` *Cancelled departure:* This column is true when the departure at this stop has been cancelled. This column is empty when no departure was scheduled.
- `Stop:Platform change` *Platform change:* This column is true when the platform of this stop has changed from the planned platform.
- `Stop:Planned platform` *Scheduled platform:* The originally scheduled platform for this service.
- `Stop:Actual platform` *Actual platform:* The platform that was actually used for this service.

In [5]:
df = pd.read_parquet('Data/no_missing_values_version1_traject_Eindhoven_sittard_2019_2025.parquet')
df.head()

,Service:RDT-ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform,departure_time,arrival_time,is_first_stop,is_last_stop,arrival_missing,departure_missing,departure_delay_missing,arrival_delay,prev_station,station_pair,arrival_delay_missing,hour,day_of_week,month,is_weekend,is_rushhour,departure_delay,is_delayed
0,738846,2019-01-01,Intercity,NS,2925,False,False,5,6220367,EKZ,Enkhuizen,NaT,NaN,None,2019-01-01 05:39:00+00:00,0.0,False,False,1,1,2019-01-01 05:39:00+00:00,NaT,True,False,True,False,False,NaN,None,None,True,5.0,1.0,1.0,0,0,0.0,False
1,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220388,BKF,Bovenkarspel Flora,2019-01-01 05:43:00+00:00,0.0,False,2019-01-01 05:43:00+00:00,0.0,False,False,1,1,2019-01-01 05:43:00+00:00,2019-01-01 05:43:00+00:00,False,False,False,False,False,0.0,EKZ,EKZ_BKF,False,5.0,1.0,1.0,0,0,0.0,False
2,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220405,BKG,Bovenkarspel-Grootebroek,2019-01-01 05:45:00+00:00,0.0,False,2019-01-01 05:47:00+00:00,0.0,False,False,2,2,2019-01-01 05:47:00+00:00,2019-01-01 05:45:00+00:00,False,False,False,False,False,0.0,BKF,BKF_BKG,False,5.0,1.0,1.0,0,0,0.0,False
3,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220435,HKS,Hoogkarspel,2019-01-01 05:52:00+00:00,0.0,False,2019-01-01 05:52:00+00:00,0.0,False,False,2,2,2019-01-01 05:52:00+00:00,2019-01-01 05:52:00+00:00,False,False,False,False,False,0.0,BKG,BKG_HKS,False,5.0,1.0,1.0,0,0,0.0,False
4,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220479,HNK,Hoorn Kersenboogerd,2019-01-01 05:58:00+00:00,1.0,False,2019-01-01 05:59:00+00:00,0.0,False,False,1,1,2019-01-01 05:59:00+00:00,2019-01-01 05:58:00+00:00,False,False,False,False,False,1.0,HKS,HKS_HNK,False,5.0,1.0,1.0,0,0,0.0,False

In [7]:
df["is_delayed"] = df["is_delayed"].astype(int)
df

,Service:RDT-ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform,departure_time,arrival_time,is_first_stop,is_last_stop,arrival_missing,departure_missing,departure_delay_missing,arrival_delay,prev_station,station_pair,arrival_delay_missing,hour,day_of_week,month,is_weekend,is_rushhour,departure_delay,is_delayed
0,738846,2019-01-01,Intercity,NS,2925,False,False,5,6220367,EKZ,Enkhuizen,NaT,NaN,None,2019-01-01 05:39:00+00:00,0.0,False,False,1,1,2019-01-01 05:39:00+00:00,NaT,True,False,True,False,False,NaN,None,None,True,5.0,1.0,1.0,0,0,0.0,0
1,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220388,BKF,Bovenkarspel Flora,2019-01-01 05:43:00+00:00,0.0,False,2019-01-01 05:43:00+00:00,0.0,False,False,1,1,2019-01-01 05:43:00+00:00,2019-01-01 05:43:00+00:00,False,False,False,False,False,0.0,EKZ,EKZ_BKF,False,5.0,1.0,1.0,0,0,0.0,0
2,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220405,BKG,Bovenkarspel-Grootebroek,2019-01-01 05:45:00+00:00,0.0,False,2019-01-01 05:47:00+00:00,0.0,False,False,2,2,2019-01-01 05:47:00+00:00,2019-01-01 05:45:00+00:00,False,False,False,False,False,0.0,BKF,BKF_BKG,False,5.0,1.0,1.0,0,0,0.0,0
3,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220435,HKS,Hoogkarspel,2019-01-01 05:52:00+00:00,0.0,False,2019-01-01 05:52:00+00:00,0.0,False,False,2,2,2019-01-01 05:52:00+00:00,2019-01-01 05:52:00+00:00,False,False,False,False,False,0.0,BKG,BKG_HKS,False,5.0,1.0,1.0,0,0,0.0,0
4,738846,2019-01-01,Intercity,NS,2925,False,False,0,6220479,HNK,Hoorn Kersenboogerd,2019-01-01 05:58:00+00:00,1.0,False,2019-01-01 05:59:00+00:00,0.0,False,False,1,1,2019-01-01 05:59:00+00:00,2019-01-01 05:58:00+00:00,False,False,False,False,False,1.0,HKS,HKS_HNK,False,5.0,1.0,1.0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2838791,16713265,2025-08-31,Intercity,NS,302957,True,True,0,151097396,EHV,Eindhoven Centraal,2025-08-31 14:57:00+00:00,0.0,True,2025-08-31 14:59:00+00:00,0.0,True,False,None,None,2025-08-31 14:59:00+00:00,2025-08-31 14:57:00+00:00,False,False,False,False,False,0.0,HT,HT_EHV,False,14.0,6.0,8.0,1,0,0.0,0
2838792,16713265,2025-08-31,Intercity,NS,302957,True,True,0,151097397,WT,Weert,2025-08-31 15:16:00+00:00,0.0,True,2025-08-31 15:16:00+00:00,0.0,True,False,None,None,2025-08-31 15:16:00+00:00,2025-08-31 15:16:00+00:00,False,False,False,False,False,0.0,EHV,EHV_WT,False,15.0,6.0,8.0,1,0,0.0,0
2838793,16713265,2025-08-31,Intercity,NS,302957,True,True,0,151097398,RM,Roermond,2025-08-31 15:29:00+00:00,0.0,True,2025-08-31 15:30:00+00:00,0.0,True,False,None,None,2025-08-31 15:30:00+00:00,2025-08-31 15:29:00+00:00,False,False,False,False,False,0.0,WT,WT_RM,False,15.0,6.0,8.0,1,0,0.0,0
2838794,16713265,2025-08-31,Intercity,NS,302957,True,True,0,151097399,STD,Sittard,2025-08-31 15:45:00+00:00,0.0,True,2025-08-31 15:46:00+00:00,0.0,True,False,None,None,2025-08-31 15:46:00+00:00,2025-08-31 15:45:00+00:00,False,False,False,False,False,0.0,RM,RM_STD,False,15.0,6.0,8.0,1,0,0.0,0
2838795,16713265,2025-08-31,Intercity,NS,302957,True,True,0,151097400,MT,Maastricht,2025-08-31 16:03:00+00:00,0.0,True,NaT,NaN,None,False,None,None,NaT,2025-08-31 16:03:00+00:00,False,True,False,True,True,0.0,STD,STD_MT,False,NaN,NaN,NaN,0,0,NaN,0

In [9]:
df["ref_time"] = df["departure_time"].fillna(df["arrival_time"])

# df = df.dropna(subset=["ref_time"])

df["ref_hour"] = df["ref_time"].dt.hour
df["ref_day_of_week"] = df["ref_time"].dt.dayofweek
df["ref_month"] = df["ref_time"].dt.month

df["ref_is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
df["ref_is_rushhour"] = df["hour"].isin([7, 8, 9, 16, 17, 18]).astype(int)

In [11]:
import numpy as np

df["ref_hour_sin"] = np.sin(2 * np.pi * df["ref_hour"] / 24)
df["ref_hour_cos"] = np.cos(2 * np.pi * df["ref_hour"] / 24)

df["ref_dow_sin"] = np.sin(2 * np.pi * df["ref_day_of_week"] / 7)
df["ref_dow_cos"] = np.cos(2 * np.pi * df["ref_day_of_week"] / 7)

df[["ref_hour", "ref_hour_sin", "ref_hour_cos", "ref_day_of_week", "ref_dow_sin", "ref_dow_cos"]].head()

,ref_hour,ref_hour_sin,ref_hour_cos,ref_day_of_week,ref_dow_sin,ref_dow_cos
0,5,0.965926,0.258819,1,0.781831,0.62349
1,5,0.965926,0.258819,1,0.781831,0.62349
2,5,0.965926,0.258819,1,0.781831,0.62349
3,5,0.965926,0.258819,1,0.781831,0.62349
4,5,0.965926,0.258819,1,0.781831,0.62349

In [13]:
from sklearn.model_selection import train_test_split

feature_cols = [
    "ref_hour_sin",
    "ref_hour_cos",
    "ref_dow_sin",
    "ref_dow_cos",
    "ref_is_weekend",
    "ref_is_rushhour",
    "ref_month",
    "is_first_stop",
    "is_last_stop"
]

X = df[feature_cols]
y = df["is_delayed"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

y_train.value_counts(normalize=True), y_test.value_counts(normalize=True)

(is_delayed
 0    0.958044
 1    0.041956
 Name: proportion, dtype: float64,
 is_delayed
 0    0.958044
 1    0.041956
 Name: proportion, dtype: float64)

In [15]:
df[feature_cols].isna().sum()

ref_hour_sin       0
ref_hour_cos       0
ref_dow_sin        0
ref_dow_cos        0
ref_is_weekend     0
ref_is_rushhour    0
ref_month          0
is_first_stop      0
is_last_stop       0
dtype: int64

In [17]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

logreg_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        class_weight="balanced"
    ))
])

logreg_clf.fit(X_train, y_train)

y_pred_lr = logreg_clf.predict(X_test)
y_proba_lr = logreg_clf.predict_proba(X_test)[:, 1]

print("=== Logistic Regression ===")
print(classification_report(y_test, y_pred_lr, digits=3))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_lr))

=== Logistic Regression ===
              precision    recall  f1-score   support

           0      0.970     0.573     0.720    543939
           1      0.057     0.589     0.104     23821

    accuracy                          0.574    567760
   macro avg      0.513     0.581     0.412    567760
weighted avg      0.931     0.574     0.695    567760

ROC-AUC: 0.6205773238438208

In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(
    class_weight="balanced"
)

rf_clf.fit(X_train, y_train)

y_pred_rf = rf_clf.predict(X_test)
y_proba_rf = rf_clf.predict_proba(X_test)[:, 1]

print("=== Random Forest ===")
print(classification_report(y_test, y_pred_rf, digits=3))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_rf))

=== Random Forest ===
              precision    recall  f1-score   support

           0      0.972     0.605     0.746    543939
           1      0.063     0.602     0.113     23821

    accuracy                          0.605    567760
   macro avg      0.517     0.603     0.429    567760
weighted avg      0.934     0.605     0.719    567760

ROC-AUC: 0.6513970848855173

### Time series

In [24]:
df_ein = df[df["Stop:Station name"] == "Eindhoven"].copy()
df_ein

,Service:RDT-ID,Service:Date,Service:Type,Service:Company,Service:Train number,Service:Completely cancelled,Service:Partly cancelled,Service:Maximum delay,Stop:RDT-ID,Stop:Station code,Stop:Station name,Stop:Arrival time,Stop:Arrival delay,Stop:Arrival cancelled,Stop:Departure time,Stop:Departure delay,Stop:Departure cancelled,Stop:Platform change,Stop:Planned platform,Stop:Actual platform,departure_time,arrival_time,is_first_stop,is_last_stop,arrival_missing,departure_missing,departure_delay_missing,arrival_delay,prev_station,station_pair,arrival_delay_missing,hour,day_of_week,month,is_weekend,is_rushhour,departure_delay,is_delayed,ref_time,ref_hour,ref_day_of_week,ref_month,ref_is_weekend,ref_is_rushhour,ref_hour_sin,ref_hour_cos,ref_dow_sin,ref_dow_cos
11,738846,2019-01-01,Intercity,NS,2925,False,False,0,6223795,EHV,Eindhoven,2019-01-01 07:59:00+00:00,4.0,False,2019-01-01 08:00:00+00:00,5.0,False,False,3,3,2019-01-01 08:00:00+00:00,2019-01-01 07:59:00+00:00,False,False,False,False,False,4.0,HT,HT_EHV,False,8.0,1.0,1.0,0,1,5.0,0,2019-01-01 08:00:00+00:00,8,1,1,0,1,0.866025,-0.500000,0.781831,0.62349
20,738954,2019-01-01,Intercity,NS,2926,False,False,0,6222842,EHV,Eindhoven,2019-01-01 07:32:00+00:00,0.0,False,2019-01-01 07:34:00+00:00,0.0,False,False,5,5,2019-01-01 07:34:00+00:00,2019-01-01 07:32:00+00:00,False,False,False,False,False,0.0,WT,WT_EHV,False,7.0,1.0,1.0,0,1,0.0,0,2019-01-01 07:34:00+00:00,7,1,1,0,1,0.965926,-0.258819,0.781831,0.62349
43,738996,2019-01-01,Intercity,NS,2929,False,False,0,6226214,EHV,Eindhoven,2019-01-01 08:59:00+00:00,3.0,False,2019-01-01 09:01:00+00:00,2.0,False,False,1,1,2019-01-01 09:01:00+00:00,2019-01-01 08:59:00+00:00,False,False,False,False,False,3.0,HT,HT_EHV,False,9.0,1.0,1.0,0,1,2.0,0,2019-01-01 09:01:00+00:00,9,1,1,0,1,0.707107,-0.707107,0.781831,0.62349
52,739092,2019-01-01,Intercity,NS,2928,False,False,0,6224040,EHV,Eindhoven,2019-01-01 08:02:00+00:00,0.0,False,2019-01-01 08:05:00+00:00,0.0,False,False,5,5,2019-01-01 08:05:00+00:00,2019-01-01 08:02:00+00:00,False,False,False,False,False,0.0,WT,WT_EHV,False,8.0,1.0,1.0,0,1,0.0,0,2019-01-01 08:05:00+00:00,8,1,1,0,1,0.866025,-0.500000,0.781831,0.62349
75,739136,2019-01-01,Intercity,NS,2931,False,False,0,6227390,EHV,Eindhoven,2019-01-01 09:29:00+00:00,1.0,False,2019-01-01 09:30:00+00:00,1.0,False,False,1,1,2019-01-01 09:30:00+00:00,2019-01-01 09:29:00+00:00,False,False,False,False,False,1.0,HT,HT_EHV,False,9.0,1.0,1.0,0,1,1.0,0,2019-01-01 09:30:00+00:00,9,1,1,0,1,0.707107,-0.707107,0.781831,0.62349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431232,3022189,2019-12-17,Intercity,NS,2975,False,False,0,26153993,EHV,Eindhoven,2019-12-17 20:28:00+00:00,0.0,False,2019-12-17 20:30:00+00:00,0.0,False,False,1,1,2019-12-17 20:30:00+00:00,2019-12-17 20:28:00+00:00,False,False,False,False,False,0.0,HT,HT_EHV,False,20.0,1.0,12.0,0,0,0.0,0,2019-12-17 20:30:00+00:00,20,1,12,0,0,-0.866025,0.500000,0.781831,0.62349
431241,3022286,2019-12-17,Intercity,NS,2974,False,False,0,26154928,EHV,Eindhoven,2019-12-17 19:32:00+00:00,0.0,False,2019-12-17 19:34:00+00:00,0.0,False,False,5,5,2019-12-17 19:34:00+00:00,2019-12-17 19:32:00+00:00,False,False,False,False,False,0.0,WT,WT_EHV,False,19.0,1.0,12.0,0,0,0.0,0,2019-12-17 19:34:00+00:00,19,1,12,0,0,-0.965926,0.258819,0.781831,0.62349
431264,3022318,2019-12-17,Intercity,NS,2977,False,False,0,26155222,EHV,Eindhoven,2019-12-17 20:58:00+00:00,0.0,False,2019-12-17 21:00:00+00:00,0.0,False,False,1,1,2019-12-17 21:00:00+00:00,2019-12-17 20:58:00+00:00,False,False,False,False,False,0.0,HT,HT_EHV,False,21.0,1.0,12.0,0,0,0.0,0,2019-12-17 21:00:00+00:00,21,1,12,0,0,-0.707107,0.707107,0.781831,0.62349
431273,3022402,2019-12-17,Intercity,NS,2976,False,False,0,26156030,EHV,Eindhoven,2019-12-17 20:02:00+00:00,0.0,False,2019-12-17 20:04:00+00:00,0.0,False,False,5,5,2019-12-17 20:04:00+00:00,2019-12-17 20:02:00+00:00,False,False,False,False,False,0.0,WT,WT_EHV,False,20.0,1.0,12.0,0,0,0.0,0,2019-12-17 20:04:00+00:00,20,1,12,0,0,-0.866025,0.500000,0.781831,0.62349
431289,3022499,2019-12-17,Intercity,NS,2978,False,False,0,26156973,EHV,Eindhoven,2019-12-17 20:32:00+00:00,5.0,False,2019-12-17 20:34:00+00:00,4.0,False,False,5,5,2019-12-17 20:34:00+00:00,2019-12-17 20:32:00+00:00,False,False,False,False,False,5.0,WT,WT_EHV,False,20.0,1.0,12.0,0,0,4.0,1,2019-12-17 20:34:00+00:00,20,1,12,0,0,-0.866025,0.500000,0.781831,0.62349

In [26]:
df_ein["ds"] = df_ein["arrival_time"].fillna(df_ein["departure_time"])

In [28]:
df_ein = df_ein.dropna(subset=["ds"])

In [ ]:
df_ein["y"] = df_ein